# Generated by Django 4.2.6 on 2023-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='is_open',
            new_name='open',
        ),
        migrations.AddField(
            model_name='store',
            name='store_slug',
            field=models.SlugField(default='www', max_length=10),
            preserve_default=False,
        ),
    ]
